'use client';

import { Eye, ShieldAlert } from 'lucide-react';
import * as React from 'react';
import { Button } from '@/components/ui/button';
import type { CoachPreview } from './use-coach';

/**
 * "Here is exactly what will be sent."
 *
 * The preview is generated by the same server function that assembles the real
 * request, so it cannot drift from what actually goes out. A student can always
 * see their own words before deciding to share them.
 */
export function SendPreview({
  preview,
  onRefresh,
}: {
  preview: CoachPreview | null;
  onRefresh: () => void;
}) {
  const [open, setOpen] = React.useState(false);

  function toggle() {
    if (!open) onRefresh();
    setOpen(!open);
  }

  return (
    <div className="rounded-[var(--radius)] border border-line bg-surface-muted px-3 py-2.5">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <p className="flex items-center gap-1.5 text-xs text-ink-muted">
          <ShieldAlert className="size-3.5 shrink-0" aria-hidden="true" />
          Only what you attach is sent. Nothing else from your workspace goes with it.
        </p>
        <Button variant="ghost" size="sm" onClick={toggle} aria-expanded={open}>
          <Eye aria-hidden="true" />
          {open ? 'Hide' : 'Show what will be sent'}
        </Button>
      </div>

      {open ? (
        <div className="mt-3 flex flex-col gap-2.5 border-t border-line pt-3">
          {preview === null ? (
            <p className="text-xs text-ink-muted">Loading the preview…</p>
          ) : preview.material.length === 0 ? (
            <p className="text-xs text-ink-muted">
              Nothing from your saved work would be attached — only the message you type.
            </p>
          ) : (
            preview.material.map((block) => (
              <div key={block.label}>
                <p className="text-xs font-medium text-ink">{block.label}</p>
                <pre className="mt-1 max-h-40 overflow-y-auto rounded-[var(--radius)] border border-line bg-surface px-2.5 py-2 text-xs whitespace-pre-wrap text-ink-muted">
                  {block.content}
                </pre>
              </div>
            ))
          )}

          {preview?.includesVoiceNotes ? (
            <p className="text-xs text-ink-muted">
              Your writing-voice notes are also included, so the coach matches how you sound.
            </p>
          ) : null}

          <p className="text-xs text-ink-subtle">
            Do not put Social Security numbers, bank details, passwords or anyone else&rsquo;s private
            information into a coaching request.
          </p>
        </div>
      ) : null}
    </div>
  );
}
